
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package compiler.parser;

import java_cup.runtime.*;
import compiler.utils.CompilerError;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\067\000\002\002\003\000\002\002\004\000\002\025" +
    "\002\000\002\025\004\000\002\024\003\000\002\024\003" +
    "\000\002\016\010\000\002\027\007\000\002\017\002\000" +
    "\002\017\003\000\002\017\005\000\002\020\005\000\002" +
    "\020\006\000\002\026\002\000\002\026\003\000\002\026" +
    "\005\000\002\031\002\000\002\031\004\000\002\030\007" +
    "\000\002\021\006\000\002\022\003\000\002\022\010\000" +
    "\002\003\002\000\002\003\004\000\002\004\003\000\002" +
    "\004\003\000\002\005\003\000\002\005\011\000\002\006" +
    "\007\000\002\006\011\000\002\007\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\007\000\002\007\003\000" +
    "\002\023\006\000\002\015\005\000\002\015\005\000\002" +
    "\015\005\000\002\015\005\000\002\015\005\000\002\015" +
    "\005\000\002\014\003\000\002\014\006\000\002\010\006" +
    "\000\002\011\005\000\002\011\005\000\002\011\003\000" +
    "\002\012\005\000\002\012\005\000\002\012\003\000\002" +
    "\013\003\000\002\013\003\000\002\013\005\000\002\013" +
    "\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\160\000\010\002\uffff\021\uffff\027\uffff\001\002\000" +
    "\010\002\001\021\011\027\013\001\002\000\004\002\006" +
    "\001\002\000\004\002\000\001\002\000\010\002\ufffd\021" +
    "\ufffd\027\ufffd\001\002\000\010\002\ufffe\021\ufffe\027\ufffe" +
    "\001\002\000\004\022\026\001\002\000\010\002\ufffc\021" +
    "\ufffc\027\ufffc\001\002\000\004\022\014\001\002\000\004" +
    "\033\015\001\002\000\006\022\017\025\020\001\002\000" +
    "\010\002\uffee\021\uffee\027\uffee\001\002\000\016\002\uffed" +
    "\005\uffed\012\uffed\013\uffed\021\uffed\027\uffed\001\002\000" +
    "\004\010\021\001\002\000\004\023\022\001\002\000\004" +
    "\011\023\001\002\000\004\015\024\001\002\000\006\022" +
    "\017\025\020\001\002\000\016\002\uffec\005\uffec\012\uffec" +
    "\013\uffec\021\uffec\027\uffec\001\002\000\004\004\027\001" +
    "\002\000\012\005\ufff9\012\ufff9\022\032\030\031\001\002" +
    "\000\006\005\042\012\041\001\002\000\004\022\036\001" +
    "\002\000\004\014\034\001\002\000\006\005\ufff8\012\ufff8" +
    "\001\002\000\006\022\017\025\020\001\002\000\006\005" +
    "\ufff6\012\ufff6\001\002\000\004\014\037\001\002\000\006" +
    "\022\017\025\020\001\002\000\006\005\ufff5\012\ufff5\001" +
    "\002\000\006\022\032\030\031\001\002\000\004\006\044" +
    "\001\002\000\010\002\ufffb\021\ufffb\027\ufffb\001\002\000" +
    "\020\006\ufff1\007\ufff1\013\ufff1\016\ufff1\020\ufff1\022\ufff1" +
    "\031\ufff1\001\002\000\020\006\uffeb\007\uffeb\013\uffeb\016" +
    "\uffeb\020\uffeb\022\uffeb\031\046\001\002\000\004\022\156" +
    "\001\002\000\016\006\044\007\063\013\062\016\060\020" +
    "\052\022\053\001\002\000\020\006\ufff0\007\ufff0\013\ufff0" +
    "\016\ufff0\020\ufff0\022\ufff0\031\ufff0\001\002\000\020\006" +
    "\uffe3\007\uffe3\013\uffe3\016\uffe3\017\uffe3\020\uffe3\022\uffe3" +
    "\001\002\000\004\004\152\001\002\000\010\004\143\010" +
    "\uffd7\032\uffd7\001\002\000\020\006\uffe2\007\uffe2\013\uffe2" +
    "\016\uffe2\017\uffe2\020\uffe2\022\uffe2\001\002\000\020\006" +
    "\uffe7\007\uffe7\013\uffe7\016\uffe7\017\uffe7\020\uffe7\022\uffe7" +
    "\001\002\000\020\006\uffe8\007\uffe8\013\uffe8\016\uffe8\017" +
    "\uffe8\020\uffe8\022\uffe8\001\002\000\020\006\uffe9\007\uffe9" +
    "\013\uffe9\016\uffe9\017\uffe9\020\uffe9\022\uffe9\001\002\000" +
    "\004\004\116\001\002\000\016\006\uffea\007\uffea\013\uffea" +
    "\016\uffea\020\uffea\022\uffea\001\002\000\020\006\uffdf\007" +
    "\uffdf\013\uffdf\016\uffdf\017\uffdf\020\uffdf\022\uffdf\001\002" +
    "\000\026\002\uffde\006\uffde\007\uffde\013\uffde\016\uffde\017" +
    "\uffde\020\uffde\021\uffde\022\uffde\027\uffde\001\002\000\020" +
    "\006\uffe1\007\uffe1\013\uffe1\016\uffe1\017\uffe1\020\uffe1\022" +
    "\uffe1\001\002\000\006\010\067\032\066\001\002\000\012" +
    "\004\076\022\075\023\071\036\074\001\002\000\012\004" +
    "\076\022\075\023\071\036\074\001\002\000\040\005\uffce" +
    "\010\067\011\uffce\012\uffce\013\uffce\033\uffce\034\uffce\035" +
    "\uffce\036\uffce\037\uffce\040\uffce\041\uffce\042\uffce\043\uffce" +
    "\044\uffce\001\002\000\036\005\uffcd\011\uffcd\012\uffcd\013" +
    "\uffcd\033\uffcd\034\uffcd\035\uffcd\036\uffcd\037\uffcd\040\uffcd" +
    "\041\uffcd\042\uffcd\043\uffcd\044\uffcd\001\002\000\036\005" +
    "\uffcf\011\uffcf\012\uffcf\013\uffcf\033\uffcf\034\uffcf\035\uffcf" +
    "\036\uffcf\037\uffcf\040\uffcf\041\uffcf\042\uffcf\043\uffcf\044" +
    "\uffcf\001\002\000\036\005\uffd2\011\uffd2\012\uffd2\013\uffd2" +
    "\033\uffd2\034\uffd2\035\uffd2\036\uffd2\037\105\040\104\041" +
    "\uffd2\042\uffd2\043\uffd2\044\uffd2\001\002\000\012\004\076" +
    "\022\075\023\071\036\074\001\002\000\040\005\uffd7\010" +
    "\uffd7\011\uffd7\012\uffd7\013\uffd7\033\uffd7\034\uffd7\035\uffd7" +
    "\036\uffd7\037\uffd7\040\uffd7\041\uffd7\042\uffd7\043\uffd7\044" +
    "\uffd7\001\002\000\012\004\076\022\075\023\071\036\074" +
    "\001\002\000\010\011\101\035\100\036\102\001\002\000" +
    "\012\004\076\022\075\023\071\036\074\001\002\000\042" +
    "\005\uffd6\010\uffd6\011\uffd6\012\uffd6\013\uffd6\032\uffd6\033" +
    "\uffd6\034\uffd6\035\uffd6\036\uffd6\037\uffd6\040\uffd6\041\uffd6" +
    "\042\uffd6\043\uffd6\044\uffd6\001\002\000\012\004\076\022" +
    "\075\023\071\036\074\001\002\000\036\005\uffd3\011\uffd3" +
    "\012\uffd3\013\uffd3\033\uffd3\034\uffd3\035\uffd3\036\uffd3\037" +
    "\105\040\104\041\uffd3\042\uffd3\043\uffd3\044\uffd3\001\002" +
    "\000\012\004\076\022\075\023\071\036\074\001\002\000" +
    "\012\004\076\022\075\023\071\036\074\001\002\000\036" +
    "\005\uffd0\011\uffd0\012\uffd0\013\uffd0\033\uffd0\034\uffd0\035" +
    "\uffd0\036\uffd0\037\uffd0\040\uffd0\041\uffd0\042\uffd0\043\uffd0" +
    "\044\uffd0\001\002\000\036\005\uffd1\011\uffd1\012\uffd1\013" +
    "\uffd1\033\uffd1\034\uffd1\035\uffd1\036\uffd1\037\uffd1\040\uffd1" +
    "\041\uffd1\042\uffd1\043\uffd1\044\uffd1\001\002\000\036\005" +
    "\uffd4\011\uffd4\012\uffd4\013\uffd4\033\uffd4\034\uffd4\035\uffd4" +
    "\036\uffd4\037\105\040\104\041\uffd4\042\uffd4\043\uffd4\044" +
    "\uffd4\001\002\000\010\005\112\035\100\036\102\001\002" +
    "\000\036\005\uffcc\011\uffcc\012\uffcc\013\uffcc\033\uffcc\034" +
    "\uffcc\035\uffcc\036\uffcc\037\uffcc\040\uffcc\041\uffcc\042\uffcc" +
    "\043\uffcc\044\uffcc\001\002\000\036\005\uffcb\011\uffcb\012" +
    "\uffcb\013\uffcb\033\uffcb\034\uffcb\035\uffcb\036\uffcb\037\uffcb" +
    "\040\uffcb\041\uffcb\042\uffcb\043\uffcb\044\uffcb\001\002\000" +
    "\010\013\115\035\100\036\102\001\002\000\020\006\uffd5" +
    "\007\uffd5\013\uffd5\016\uffd5\017\uffd5\020\uffd5\022\uffd5\001" +
    "\002\000\012\004\076\022\075\023\071\036\074\001\002" +
    "\000\004\005\135\001\002\000\022\033\121\034\126\035" +
    "\100\036\102\041\122\042\123\043\125\044\124\001\002" +
    "\000\012\004\076\022\075\023\071\036\074\001\002\000" +
    "\012\004\076\022\075\023\071\036\074\001\002\000\012" +
    "\004\076\022\075\023\071\036\074\001\002\000\012\004" +
    "\076\022\075\023\071\036\074\001\002\000\012\004\076" +
    "\022\075\023\071\036\074\001\002\000\012\004\076\022" +
    "\075\023\071\036\074\001\002\000\010\005\uffdc\035\100" +
    "\036\102\001\002\000\010\005\uffd9\035\100\036\102\001" +
    "\002\000\010\005\uffd8\035\100\036\102\001\002\000\010" +
    "\005\uffda\035\100\036\102\001\002\000\010\005\uffdb\035" +
    "\100\036\102\001\002\000\010\005\uffdd\035\100\036\102" +
    "\001\002\000\014\006\044\013\062\016\060\020\052\022" +
    "\053\001\002\000\020\006\uffe9\007\uffe9\013\uffe9\016\uffe9" +
    "\017\140\020\uffe9\022\uffe9\001\002\000\020\006\uffe5\007" +
    "\uffe5\013\uffe5\016\uffe5\017\uffe5\020\uffe5\022\uffe5\001\002" +
    "\000\014\006\044\013\062\016\060\020\052\022\053\001" +
    "\002\000\020\006\uffe4\007\uffe4\013\uffe4\016\uffe4\017\uffe4" +
    "\020\uffe4\022\uffe4\001\002\000\020\006\uffe6\007\uffe6\013" +
    "\uffe6\016\uffe6\017\uffe6\020\uffe6\022\uffe6\001\002\000\016" +
    "\004\076\005\ufff4\012\ufff4\022\075\023\071\036\074\001" +
    "\002\000\006\005\147\012\146\001\002\000\012\005\ufff3" +
    "\012\ufff3\035\100\036\102\001\002\000\012\004\076\022" +
    "\075\023\071\036\074\001\002\000\004\013\150\001\002" +
    "\000\020\006\ufffa\007\ufffa\013\ufffa\016\ufffa\017\ufffa\020" +
    "\ufffa\022\ufffa\001\002\000\012\005\ufff2\012\ufff2\035\100" +
    "\036\102\001\002\000\012\004\076\022\075\023\071\036" +
    "\074\001\002\000\004\005\154\001\002\000\014\006\044" +
    "\013\062\016\060\020\052\022\053\001\002\000\020\006" +
    "\uffe0\007\uffe0\013\uffe0\016\uffe0\017\uffe0\020\uffe0\022\uffe0" +
    "\001\002\000\004\014\157\001\002\000\006\022\017\025" +
    "\020\001\002\000\004\013\161\001\002\000\020\006\uffef" +
    "\007\uffef\013\uffef\016\uffef\020\uffef\022\uffef\031\uffef\001" +
    "\002\000\006\005\ufff7\012\ufff7\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\160\000\006\002\004\025\003\001\001\000\010\016" +
    "\011\021\006\024\007\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\022\015\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\022\024\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\017\027\020\032\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\022\034\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\022\037\001\001\000\002\001" +
    "\001\000\004\020\161\001\001\000\004\023\042\001\001" +
    "\000\002\001\001\000\004\031\044\001\001\000\006\003" +
    "\046\030\047\001\001\000\002\001\001\000\022\004\060" +
    "\005\056\006\055\007\054\010\050\014\064\023\053\027" +
    "\063\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\011\113\012\072" +
    "\013\071\014\067\001\001\000\012\011\076\012\072\013" +
    "\071\014\067\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\013\112\014" +
    "\067\001\001\000\002\001\001\000\012\011\110\012\072" +
    "\013\071\014\067\001\001\000\002\001\001\000\010\012" +
    "\107\013\071\014\067\001\001\000\002\001\001\000\010" +
    "\012\102\013\071\014\067\001\001\000\002\001\001\000" +
    "\006\013\106\014\067\001\001\000\006\013\105\014\067" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\011\117\012" +
    "\072\013\071\014\067\015\116\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\011\133\012\072\013\071\014" +
    "\067\001\001\000\012\011\132\012\072\013\071\014\067" +
    "\001\001\000\012\011\131\012\072\013\071\014\067\001" +
    "\001\000\012\011\130\012\072\013\071\014\067\001\001" +
    "\000\012\011\127\012\072\013\071\014\067\001\001\000" +
    "\012\011\126\012\072\013\071\014\067\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\022\004\136" +
    "\005\135\006\055\007\054\010\050\014\064\023\053\027" +
    "\063\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\005\141\006\140\007\054\010\050\014\064\023\053\027" +
    "\063\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\011\144\012\072\013\071\014\067\026\143\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\011\150\012\072" +
    "\013\071\014\067\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\011\117\012\072\013\071" +
    "\014\067\015\152\001\001\000\002\001\001\000\022\004" +
    "\154\005\056\006\055\007\054\010\050\014\064\023\053" +
    "\027\063\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\022\157\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol token) {
        throw CompilerError.SyntaxError(token.left, token.right);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= top_decl_list 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // top_decl_list ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("top_decl_list",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // top_decl_list ::= top_decl_list top_decl 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("top_decl_list",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // top_decl ::= type_decl 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("top_decl",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // top_decl ::= procedure_decl 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("top_decl",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // procedure_decl ::= PROC IDENT LPAREN param_list RPAREN statement_block 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("procedure_decl",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // procedure_call ::= IDENT LPAREN args_list RPAREN SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("procedure_call",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // param_list ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param_list",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // param_list ::= param 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param_list",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // param_list ::= param_list COMMA param 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param_list",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // param ::= IDENT COLON type_expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // param ::= REF IDENT COLON type_expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // args_list ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("args_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // args_list ::= expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("args_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // args_list ::= args_list COMMA expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("args_list",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // var_decl_list ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_decl_list",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // var_decl_list ::= var_decl_list var_decl 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_decl_list",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // var_decl ::= VAR IDENT COLON type_expr SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_decl",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // type_decl ::= TYPE IDENT EQ type_expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type_decl",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // type_expr ::= IDENT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type_expr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // type_expr ::= ARRAY LBRACKET INTLIT RBRACKET OF type_expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type_expr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // statement_list ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // statement_list ::= statement_list statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // statement ::= matched_statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // statement ::= unmatched_statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // matched_statement ::= non_if_statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("matched_statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // matched_statement ::= IF LPAREN condition RPAREN matched_statement ELSE matched_statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("matched_statement",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // unmatched_statement ::= IF LPAREN condition RPAREN statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("unmatched_statement",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // unmatched_statement ::= IF LPAREN condition RPAREN matched_statement ELSE unmatched_statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("unmatched_statement",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // non_if_statement ::= assign_statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("non_if_statement",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // non_if_statement ::= statement_block 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("non_if_statement",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // non_if_statement ::= procedure_call 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("non_if_statement",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // non_if_statement ::= WHILE LPAREN condition RPAREN statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("non_if_statement",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // non_if_statement ::= SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("non_if_statement",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // statement_block ::= LCURLY var_decl_list statement_list RCURLY 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_block",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // condition ::= expression EQ expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // condition ::= expression NEQ expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // condition ::= expression LT expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // condition ::= expression GT expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // condition ::= expression LEQ expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // condition ::= expression GEQ expression 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // lvalue ::= IDENT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lvalue",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // lvalue ::= lvalue LBRACKET expression RBRACKET 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lvalue",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // assign_statement ::= lvalue ASGN expression SEMICOLON 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assign_statement",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expression ::= expression PLUS term 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expression ::= expression MINUS term 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expression ::= term 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // term ::= term STAR factor 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // term ::= term SLASH factor 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // term ::= factor 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // factor ::= lvalue 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // factor ::= INTLIT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // factor ::= LPAREN expression RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // factor ::= MINUS factor 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
