
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler.parser;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int SLASH = 7;
  public static final int IDENT = 8;
  public static final int SEMIC = 3;
  public static final int INTLIT = 9;
  public static final int STAR = 6;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int error = 1;
  public static final int ASGN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASGN",
  "SEMIC",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "IDENT",
  "INTLIT"
  };
}

